# Generated by Django 4.1 on 2022-09-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Leave a review?'),
        ),
    ]
