# Generated by Django 4.1 on 2022-09-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='review',
        ),
    ]
