# Generated by Django 4.1 on 2022-09-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetReviews',
        ),
    ]
