# Generated by Django 4.1 on 2022-08-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0002_alter_ahgametrack_game_type_alter_ahgametrack_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahgametrack',
            name='score',
            field=models.IntegerField(default=10),
        ),
    ]
