# Generated by Django 4.1 on 2022-08-30 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagramhunt', '0003_alter_ahgametrack_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahgametrack',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_gametracking', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ahgametrack',
            name='score',
            field=models.IntegerField(),
        ),
    ]
