# Generated by Django 4.1 on 2022-08-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0004_ahgametrack_user_alter_ahgametrack_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahgametrack',
            name='score',
            field=models.CharField(max_length=3),
        ),
    ]
