# Generated by Django 4.1 on 2022-09-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0005_alter_ahgametrack_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ahGameTrack',
        ),
    ]
