# Generated by Django 4.1 on 2022-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addscore',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
