# Generated by Django 4.1 on 2022-09-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addreview',
            old_name='user',
            new_name='login',
        ),
    ]
