# Generated by Django 4.1 on 2022-09-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_user_addreview_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreview',
            name='login',
            field=models.CharField(max_length=20),
        ),
    ]
