# Generated by Django 4.1 on 2022-09-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddScoreM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, default='')),
                ('scoreM', models.PositiveSmallIntegerField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
